package com.riot.dto.Match

class Challenges {
	int twelveAssistStreakCount // 12AssistStreakCount in Riot Api
	int baronBuffGoldAdvantageOverThreshold
	float controlWardTimeCoverageInRiverOrEnemyHalf
	int earliestBaron
	int earliestDragonTakedown
	int earliestElderDragon
	int earlyLaningPhaseGoldExpAdvantage
	int fasterSupportQuestCompletion
	int fastestLegendary
	int hadAfkTeammate
	int highestChampionDamage
	int highestCrowdControlScore
	int highestWardKills
	int junglerKillsEarlyJungle
	int killsOnLanersEarlyJungleAsJungler
	int laningPhaseGoldExpAdvantage
	int legendaryCount
	float maxCsAdvantageOnLaneOpponent
	int maxLevelLeadLaneOpponent
	int mostWardsDestroyedOneSweeper
	int mythicItemUsed
	int playedChampSelectPosition
	int soloTurretsLategame
	int takedownsFirst25Minutes
	int teleportTakedowns
	int thirdInhibitorDestroyedTime
	int threeWardsOneSweeperCount
	float visionScoreAdvantageLaneOpponent
	int InfernalScalePickup
	int fistBumpParticipation
	int voidMonsterKill
	int abilityUses
	int acesBefore15Minutes
	float alliedJungleMonsterKills
	int baronTakedowns
	int blastConeOppositeOpponentCount
	int bountyGold
	int buffsStolen
	int completeSupportQuestInTime
	int controlWardsPlaced
	float damagePerMinute
	float damageTakenOnTeamPercentage
	int dancedWithRiftHerald
	int deathsByEnemyChamps
	int dodgeSkillShotsSmallWindow
	int doubleAces
	int dragonTakedowns
	int[] legendaryItemUsed
	float effectiveHealAndShielding
	int elderDragonKillsWithOpposingSoul
	int elderDragonMultikills
	int enemyChampionImmobilizations
	float enemyJungleMonsterKills
	int epicMonsterKillsNearEnemyJungler
	int epicMonsterKillsWithin30SecondsOfSpawn
	int epicMonsterSteals
	int epicMonsterStolenWithoutSmite
	int firstTurretKilled
	float firstTurretKilledTime
	int flawlessAces
	int fullTeamTakedown
	float gameLength
	int getTakedownsInAllLanesEarlyJungleAsLaner
	float goldPerMinute
	int hadOpenNexus
	int immobilizeAndKillWithAlly
	int initialBuffCount
	int initialCrabCount
	float jungleCsBefore10Minutes
	int junglerTakedownsNearDamagedEpicMonster
	float kda
	int killAfterHiddenWithAlly
	int killedChampTookFullTeamDamageSurvived
	int killingSprees
	float killParticipation
	int killsNearEnemyTurret
	int killsOnOtherLanesEarlyJungleAsLaner
	int killsOnRecentlyHealedByAramPack
	int killsUnderOwnTurret
	int killsWithHelpFromEpicMonster
	int knockEnemyIntoTeamAndKill
	int kTurretsDestroyedBeforePlatesFall
	int landSkillShotsEarlyGame
	int laneMinionsFirst10Minutes
	int lostAnInhibitor
	int maxKillDeficit
	int mejaisFullStackInTime
	float moreEnemyJungleThanOpponent
	int multiKillOneSpell // This is an offshoot of the OneStone challenge. The code checks if a spell with the same instance ID does the final point of damage to at least 2 Champions. It doesn't matter if they're enemies, but you cannot hurt your friends.
	int multikills
	int multikillsAfterAggressiveFlash
	int multiTurretRiftHeraldCount
	int outerTurretExecutesBefore10Minutes
	int outnumberedKills
	int outnumberedNexusKill
	int perfectDragonSoulsTaken
	int perfectGame
	int pickKillWithAlly
	int poroExplosions
	int quickCleanse
	int quickFirstTurret
	int quickSoloKills
	int riftHeraldTakedowns
	int saveAllyFromDeath
	int scuttleCrabKills
	float shortestTimeToAceFromFirstTakedown
	int skillshotsDodged
	int skillshotsHit
	int snowballsHit
	int soloBaronKills
	int SWARM_DefeatAatrox
	int SWARM_DefeatBriar
	int SWARM_DefeatMiniBosses
	int SWARM_EvolveWeapon
	int SWARM_Have3Passives
	int SWARM_KillEnemy
	float SWARM_PickupGold
	int SWARM_ReachLevel50
	int SWARM_Survive15Min
	int SWARM_WinWith5EvolvedWeapons
	int soloKills
	int stealthWardsPlaced
	int survivedSingleDigitHpCount
	int survivedThreeImmobilizesInFight
	int takedownOnFirstTurret
	int takedowns
	int takedownsAfterGainingLevelAdvantage
	int takedownsBeforeJungleMinionSpawn
	int takedownsFirstXMinutes
	int takedownsInAlcove
	int takedownsInEnemyFountain
	int teamBaronKills
	float teamDamagePercentage
	int teamElderDragonKills
	int teamRiftHeraldKills
	int tookLargeDamageSurvived
	int turretPlatesTaken
	int turretsTakenWithRiftHerald // Any player who damages a tower that is destroyed within 30 seconds of a Rift Herald charge will receive credit. A player who does not damage the tower will not receive credit.
	int turretTakedowns
	int twentyMinionsIn3SecondsCount
	int twoWardsOneSweeperCount
	int unseenRecalls
	float visionScorePerMinute
	int wardsGuarded
	int wardTakedowns
	int wardTakedownsBefore20M
}
