package com.riot.dto.Match

class ParticipantStats
{
	int item0
	int item2
	int totalUnitsHealed
	int item1
	int largestMultiKill
	int goldEarned
	boolean firstInhibitorKill
	long physicalDamageTaken
	int nodeNeutralizeAssist
	int totalPlayerScore
	int champLevel
	long damageDealtToObjectives
	long totalDamageTaken
	int neutralMinionsKilled
	int deaths
	int tripleKills
	long magicDamageDealtToChampions
	int wardsKilled
	int pentaKills
	long damageSelfMitigated
	int largestCriticalStrike
	int nodeNeutralize
	int totalTimeCrowdControlDealt
	boolean firstTowerKill
	long magicDamageDealt
	int totalScoreRank
	int nodeCapture
	int wardsPlaced
	long totalDamageDealt
	long timeCCingOthers
	long magicalDamageTaken
	int largestKillingSpree
	long totalDamageDealtToChampions
	long physicalDamageDealtToChampions
	int neutralMinionsKilledTeamJungle
	int totalMinionsKilled
	boolean firstInhibitorAssist
	int visionWardsBoughtInGame
	int objectivePlayerScore
	int kills
	boolean firstTowerAssist
	int combatPlayerScore
	int inhibitorKills
	int turretKills
	int participantId
	long trueDamageTaken
	boolean firstBloodAssist
	int nodeCaptureAssist
	int assists
	int teamObjective
	int altarsNeutralized
	int goldSpent
	long damageDealtToTurrets
	int altarsCaptured
	boolean win
	long totalHeal
	int unrealKills
	long visionScore
	long physicalDamageDealt
	boolean firstBloodKill
	int longestTimeSpentLiving
	int killingSprees
	int sightWardsBoughtInGame
	long trueDamageDealtToChampions
	int neutralMinionsKilledEnemyJungle
	int doubleKills
	long trueDamageDealt
	int quadraKills
	int item4
	int item3
	int item6
	int item5
	int playerScore0
	int playerScore1
	int playerScore2
	int playerScore3
	int playerScore4
	int playerScore5
	int playerScore6
	int playerScore7
	int playerScore8
	int playerScore9
	int perk0
	int perk0Var1
	int perk0Var2
	int perk0Var3
	int perk1
	int perk1Var1
	int perk1Var2
	int perk2
	int perk2Var1
	int perk2Var2
	int perk2Var3
	int perk3
	int perk3Var1
	int perk3Var2
	int perk3Var3
	int perk4
	int perk4Var1
	int perk4Var2
	int perk4Var3
	int perk5
	int perk5Var1
	int perk5Var2
	int perk5Var3
	int perkPrimaryStyle
	int perkSubStyle
}
