package com.riot.dto.Match

class ParticipantStats
{
	long physicalDamageDealt
	int neutralMinionsKilledTeamJungle
	long magicDamageDealt
	int totalPlayerScore
	int deaths
	boolean win
	int neutralMinionsKilledEnemyJungle
	int altarsCaptured
	int largestCriticalStrike
	long totalDamageDealt
	long magicDamageDealtToChampions
	int visionWardsBoughtInGame
	long damageDealtToObjectives
	int largestKillingSpree
	int item1
	int quadraKills
	int teamObjective
	int totalTimeCrowdControlDealt
	int longestTimeSpentLiving
	int wardsKilled
	boolean firstTowerAssist
	boolean firstTowerKill
	int item2
	int item3
	int item0
	boolean firstBloodAssist
	long visionScore
	int wardsPlaced
	int item4
	int item5
	int item6
	int turretKills
	int tripleKills
	long damageSelfMitigated
	int champLevel
	int nodeNeutralizeAssist
	boolean firstInhibitorKill
	int goldEarned
	long magicalDamageTaken
	int kills
	int doubleKills
	int nodeCaptureAssist
	long trueDamageTaken
	int nodeNeutralize
	boolean firstInhibitorAssist
	int assists
	int unrealKills
	int neutralMinionsKilled
	int objectivePlayerScore
	int combatPlayerScore
	long damageDealtToTurrets
	int altarsNeutralized
	long physicalDamageDealtToChampions
	int goldSpent
	long trueDamageDealt
	long trueDamageDealtToChampions
	int participantId
	int pentaKills
	long totalHeal
	int totalMinionsKilled
	boolean firstBloodKill
	int nodeCapture
	int largestMultiKill
	int sightWardsBoughtInGame
	long totalDamageDealtToChampions
	int totalUnitsHealed
	int inhibitorKills
	int totalScoreRank
	long totalDamageTaken
	int killingSprees
	long timeCCingOthers
	long physicalDamageTaken
}
