package com.riot.enums;

public enum METHOD
{
	API_SHORT,
	API_LONG,
	STATIC,
	CHAMPION_MASTERIES_BY_SUMMONER_ID,
	MATCH_BY_MATCH_ID,
	MATCH_TIMELINE_BY_MATCH_ID,
	MATCH_LIST_BY_ACCOUNT_ID,
	SUMMONER_BY_NAME
}
