package com.riot.enums;

public enum METHOD
{
	API_SHORT,
	API_LONG,
	STATIC,
	ACCOUNT_BY_NAME,
	CHAMPION_MASTERIES_BY_SUMMONER_ID,
	MATCH_BY_MATCH_ID,
	MATCH_TIMELINE_BY_MATCH_ID,
	MATCHES_BY_PUUID,
	SUMMONER_BY_NAME
}
